src/qt/forms/optionsdialog.ui
src/qt/optionsdialog.cpp
src/qt/optionsdialog.h
src/qt/optionsmodel.cpp
src/qt/transactionview.cpp

https://explorer-eu.avn.network/ and https://explorer-us.avn.network/ set as defaults.

GUI: Add out-of-the-box browsers. Can be changed and removed in options

---

src/qt/transactionview.cpp

backport from bitcoin pr #9683

[backport] gui, wallet: random abort (segmentation fault) btc#9683

---

configure.ac

backport from bitcoin pr #9683

build: Suppress -Wdeprecated-copy warnings

---

src/random.h
src/test/random_tests.cpp
src/wallet/wallet.cpp

Backport part of bitcoin#14624
bitcoin#3db746beb407f7cdd9cd6a605a195bef1254b4c0

Introduce a Shuffle for FastRandomContext and use it in wallet

---

src/net_processing.cpp
src/qt/guiconstants.h
src/qt/transactiondesc.cpp
src/qt/transactionrecord.cpp
src/qt/transactionrecord.h
src/qt/transactiontablemodel.cpp
src/validationinterface.cpp
src/validationinterface.h
src/wallet/wallet.cpp
src/wallet/wallet.h

Manual backport of https://github.com/bitcoin/bitcoin/commit/beef7ec4be725beea870a2da510d2817487601ec
CVE-2018-17145

Backport: Remove useless mapRequest tracking

---

src/wallet/wallet.h

Manual backport of bitcoin PR #16572

backport: wallet: Fix Char as Bool in Wallet

---

src/rpc/server.cpp

manual backport of bitcoin PR # 14993
rpc: Fix data race (UB) in InterruptRPC()

backport: rpc: Fix data race (UB) in InterruptRPC()

---

depends/packages/expat.mk
doc/dependencies.md

depends: update expat to 2.4.1

---

depends/packages/libevent.mk
doc/dependencies.md

Update libevent to 2.1.12-stable.
https://raw.githubusercontent.com/libevent/libevent/release-2.1.12-stable/ChangeLog

depends: libevent update

---

contrib/install_db4.sh
src/qt/askpassphrasedialog.cpp

* Contrib: Copy install_db4.sh from bitcoin.
This script automates the process of downloading and compiling Berkeley DB 4.8.
Rebranded to Avian

Contrib: Copy install_db4.sh from bitcoin

---

src/httpserver.cpp
src/qt/askpassphrasedialog.cpp

backport of bitcoin#19033.
This fixes a race between http_request_cb and StopHTTPServer where
the work queue is used after release. - promag @ bitcoin.

http: Release work queue after event base finish (btc#19033)

---

src/qt/askpassphrasedialog.cpp
src/script/interpreter.cpp

Commented the line, if it is needed it should be easy to re-enable.
Fixes #34

disable output to stdout

---

src/qt/ravengui.cpp

* Set stylesheet for price
* Increase update interval to 30 sec.

gui: set stylesheet for price and increase to 30s update times.

---

src/qt/ravengui.cpp

Revert "gui: set black text for price and increase to 30s update times."

---

src/qt/ravengui.cpp

* Set black text color for price
* Increase update interval to 30 sec.

gui: set black text for price and increase to 30s update times.

---

src/Makefile.am
src/algo/crow/minotaurx.h
src/primitives/block.cpp

Rename crow.h to minotaurx.h

---

.github/workflows/codeql-analysis.yml

This creates a CodeQL action to analyze code for security issues, and many more. Merging this PR urgently once the checks pass. It is crucial that new code be checked by CodeQL.

ci: Create CodeQL action to analyze code

---

src/validation.cpp

Based on https://github.com/bitcoin/bitcoin/pull/15471

qt: Remove 'Unknown block versions being mined' warning

---

src/flightplans/flightplans.cpp

Fixes #104 
Don't open all Lua libs for security purpose.

afp: Do not include all lua libraries

---

src/rpc/rawtransaction.cpp

This PR restores FORKID to `createrawtranscation`, fixing this bug when using this RPC method:
```
Illegal use of SIGHASH_FORKID
```
This was a regression in 4.x since this code was included in 3.x.

rpc: Restore FORKID to createrawtransaction

---

.github/workflows/c-cpp.yml

Update image to ubuntu-22.04 due to #116

ci: Update image to ubuntu-22.04

---

share/qt/Info.plist.in

backport: [qt] osx darkmode

---

src/random.h
src/test/random_tests.cpp
src/wallet/wallet.cpp

Backport part of bitcoin#14624
Cherry pick of #17

cherry-pick: Introduce a Shuffle for FastRandomContext and use it in wallet 

---

depends/packages/expat.mk
doc/dependencies.md

CVE-2019-15903
CVE-2018-20843
(cherry picked from commit d634ccddc3aa51a57c533ed1d78674d97255d7b1)

depends: update expat to 2.4.1 (#31)

---

src/httpserver.cpp

* http: Release work queue after event base finish (btc#19033)
backport of bitcoin#19033.
This fixes a race between http_request_cb and StopHTTPServer where
the work queue is used after release. - promag @ bitcoin.
(cherry picked from commit 994f5b44fbf2d1220bdf5982b90cc45eb58501e6)

cherry-pick: http: Release work queue after event base finish (btc#19033) (#38)

---

src/qt/reissueassetdialog.cpp

Backport
>    Update asset list when the qcombobox is shown.

backport: [qt]  Update asset list when qcombobox is shown.

---

src/qt/aviangui.cpp
src/qt/guiconstants.h
src/qt/res/css/Dark.css
src/qt/res/css/Light.css

This PR cleans up the UI and introduces new design elements. Opening this PR as a draft to discuss changes. If anyone doesn't agree with the UI changes, feel free to comment.
Before:
After:

qt: 4.1 UI cleanup

---

src/qt/avian.cpp
src/qt/aviangui.cpp
src/qt/aviangui.h
src/qt/forms/debugwindow.ui
src/qt/rpcconsole.cpp
src/qt/rpcconsole.h

This PR adds a wallet repair tab with multiple options for wallet repair and blockchain reindex.
*Backport and modified from Dash PR 342.*
Screenshot:

qt: Add wallet repair tab

---

doc/release-notes/release-notes-4.1.0.md

This PR adds the release notes for 4.1. This PR will stay in draft until all PRs requested by #169 are merged.

docs: Add release notes for 4.1
