AvianNetwork/Avian

- src/chainparams.cpp
Some new blocks were found so need to adjust the target block.
- Was 275106
- Now 275109
> Alter block height for diffRetargetFix

- src/support/lockedpool.cpp
Manual backport of bitcoin PR#18443 and bitcoin PR#15633.
Use madvise on Linux and FreeBSD to avoid sensitive data from secure_allocator to be written to swap and core-files.
https://github.com/bitcoin/bitcoin/pull/15600/commits/d831831822885717e9841f1ff67c19add566fa45
https://github.com/bitcoin/bitcoin/pull/18443/commits/f85203097f78d9daa1d35c4097a80beab31da2a4
> lockedpool: avoid sensitive data in core files (Linux and FreeBSD)

- src/net.h
Manual backport of bitcoin PR #17906
Initialize CConnman byte counters during construction, so GetTotalBytesRecv()
and GetTotalBytesSent() methods don't return garbage before Start() is called.
Change shouldn't have any effect outside of the GUI. It just fixes a race
condition during a qt test that was observed on travis:
https://travis-ci.org/bitcoin/bitcoin/jobs/634989685
> backport: gui: Set CConnman byte counters earlier to avoid uninitialized reads

- src/netaddress.cpp
- src/netaddress.h
Manual backport of bitcoin PR 14728
Reachable from either place where SetIP is used when our best-guess
addrLocal for a peer is IPv4, but the peer tells us it's reaching us at
an IPv6 address.
In that case, SetIP turns an IPv4 address into an IPv6 address without
setting the scopeId, which is subsequently read in GetSockAddr during
CNetAddr::ToStringIP and passed to getnameinfo. Fix by ensuring every
constructor initializes the scopeId field with something.
> backport: fix uninitialized read when stringifying an addrLocal

- src/net.h
- src/net_processing.cpp
Manual backport of bitcoin PR #13907
The largest sensible size for a locator is log in the number of blocks.
But, as noted by Coinr8d on BCT a maximum size message could encode a
hundred thousand locators.  If height were used to limit the messages
that could open new attacks where peers on long low diff forks would
get disconnected and end up stuck.
Ideally, nodes first first learn to limit the size of locators they
send before limiting what would be processed, but common implementations
back off with an exponent of 2 and have an implicit limit of 2^32
blocks, so they already cannot produce locators over some size.
This sets the limit to an absurdly high amount of 101 in order to
maximize compatibility with existing software.
> backport: Introduce a maximum size for locators.

- src/pow.cpp
- src/qt/askpassphrasedialog.cpp
Disable logging of diff to debug.log.
Filling the log with all this makes debugging other issues harder.
Can be re-enabled easily if necessary.
Example from debug.log:
> disable logging of diff

- src/qt/ravengui.cpp
* My previous fix broke dark-mode.
* This one fetches the textcolor from platformStyle.
Co-authored-by: Julepalme <50538512+Julepalme@users.noreply.github.com>
> gui: text color for price info fixed for dark and light mode.

- src/qt/walletmodeltransaction.cpp
- src/qt/walletmodeltransaction.h
Backport of bitcoin PR #10920
https://github.com/bitcoin/bitcoin/pull/10920
> backport: [qt] Fix potential memory leak in newPossibleKey(ChangeCWallet *wallet) (bitcoin #10920)

- src/qt/darkstyle.cpp
- src/qt/raven.cpp
Set attributes before invoking the application.
This way, they work.
Disable increased font-size in dark-mode.
> GUI: Enable High DPI Scaling

- src/chainparams.cpp
- src/primitives/block.cpp
- src/qt/splashscreen.cpp
This PR allows `regtest` or regression test to run without any assert fails. This is important to merge *urgently* since it is a blocker PR to enable our testing framework for it to work properly.  Mainnet and Testnet work fine without any assert fails.
> Fix regression test in 4.1

- src/qt/guiconstants.h
This PR uses the correct explorer URLs.
Merging once checks pass since it's a non-breaking change.
> Qt: Use correct AVN browser URLs

- src/lua/loslib.c
This fixes a error messaging when linking avian during the build process:
```bash
warning: the use of 'tmpnam' is dangerous, better use 'mkstemp'
```
Our targets (Linux, Mingw-w64, Darwin) support POSIX standards. The Microsoft Visual C++  Compiler (MSVC) does not support POSIX `mkstemp`; however, using the Mingw-w64 (gcc) compiler supports POSIX `mkstemp`. The CI/CD should verify if a windows binary is built successfully. (since it uses mingw-w64).
Loosing support for MSVC can be addressed in a different issue or PR if it becomes a problem in the future.
> lua: Use POSIX mkstemp instead of tmpnam

- .github/workflows/codeql-analysis.yml
Update CodeQL action to v2 since v1 will be out of support on Dec 2022.
> ci: Update CodeQL action to v2

- src/qt/forms/debugwindow.ui
- src/qt/peertablemodel.cpp
- src/qt/peertablemodel.h
- src/qt/rpcconsole.cpp
This PR improves the peer tab by adding:
- Direction column and icon showing if a peer is inbound or outbound.
- "Copy address" to context menu when right-clicking a peer.
- Elide long strings in their middle in peers tab
These changes were back-ported from Bitcoin and tested to work. If there is more peer tab changes from Bitcoin we can backport, feel free to open a PR or comment here.
> Qt: Improve peer tab

- src/qt/forms/optionsdialog.ui
- src/qt/guiconstants.h
- src/qt/optionsdialog.cpp
- src/qt/optionsdialog.h
- src/qt/optionsmodel.cpp
- src/qt/optionsmodel.h
This adds a prune setting to the options dialog. Backport from [Bitcoin PR#13043](https://github.com/bitcoin/bitcoin/pull/13043)
> Qt: Add prune setting to OptionsDialog

- src/qt/overviewpage.cpp
This PR forces the asset background (in overview page) to be same color regardless if it's admin. An icon is already shown if the asset is admin.
Would like thoughts on this change.
> Qt: Use common gradient for assets in overview page

- src/rpc/client.cpp
- src/wallet/rpcwallet.cpp
Creates new RPC method that:
Returns all transactions in the wallet that do not have a mempool entry.
Based on work done by me for https://github.com/dogecoin/dogecoin/pull/2988
> Add RPC method showing wallet TX not in mempool

- src/net.cpp
- src/net.h
- src/net_processing.cpp
- src/net_processing.h
- src/rpc/net.cpp
This PR backports the relevant Bitcoin Core code (from [0d64b8f7](https://github.com/bitcoin/bitcoin/commit/0d64b8f7), [5648138f](https://github.com/bitcoin/bitcoin/commit/5648138f), [f424d601](https://github.com/bitcoin/bitcoin/commit/f424d601))
The Bitcoin PR states:
> This commit introduces a "token bucket" rate limiter for the
processing of addresses in incoming ADDR and ADDRV2 messages.
Every connection gets an associated token bucket. Processing an
address in an ADDR or ADDRV2 message from non-whitelisted peers
consumes a token from the bucket. If the bucket is empty, the
address is ignored (it is not forwarded or processed). The token
counter increases at a rate of 0.1 tokens per second, and will
accrue up to a maximum of 1000 tokens (the maximum we accept in a
single ADDR or …
> Rate limit processing incoming addr messages

- src/chainparams.cpp
- src/chainparams.h
- src/consensus/consensus.h
- src/consensus/params.h
- src/init.cpp
- src/validation.cpp
- src/validation.h
This PR adds working:
`AreMessagesDeployed()`
`AreRestrictedAssetsDeployed()`
This PR also converts the respective chain params from block height to a timestamp for consistency.
During my testing, message was correctly enabled and disabled on mainnet, testnet, and regtest.
However, the message below can be misleading and I have put a *TODO* to fix it later. *(issue more complex them it seems and more testing required which is out of scope of this PR).*  This should not effect the actual `AreMessagesDeployed()` from providing correct boolean values.
https://github.com/AvianNetwork/Avian/blob/5aa0e4aa4040c1f3f1f71b0aa1a6edf2e86875d2/src/init.cpp#L1622
> Introduce proper AreMessagesDeployed() and AreRestrictedAssetsDeployed()

- src/chainparams.cpp
- src/consensus/params.h
- src/rpc/blockchain.cpp
- src/validation.cpp
- src/versionbits.cpp
- src/versionbits.h
No need for versionbits checking since we are doing timestamp-based hardforks.
This does not effect functionally of dual-algo or assets (testnet). This cleans up our codebase since we rely on timestamp-based hardforks instead of using versionbits. (We should aim to use versionbits for any future hardfork unless if the hardfork is accepted by the community.)
> params: Remove versionbits for assets and crow

- src/algo/sph_sha2.h
- src/assets/assets.cpp
- src/pow.cpp
- src/txdb.cpp
Avian Core <= 3.1.0 uses `RVN` as the main asset. This would cause pre-4.0.0 inputs that haven't been reindex/rescan to appear as `RVN` and not `AVN` causing the wallet to think it's an asset.
> Add backward compatibility with ReadAddressUnspentIndex

- src/qt/forms/debugwindow.ui
- src/qt/res/css/Dark.css
- src/qt/res/css/Light.css
This PR improves the RPC console by making the buttons look clickable and using a dark background - if on dark mode.
> qt: Improve RPC console

- src/qt/aviangui.cpp
- src/qt/forms/openuridialog.ui
- src/qt/openuridialog.cpp
- src/qt/openuridialog.h
This PR reworks the `Open URI` dialog by removing the file selector and adding a button to paste the active clipboard.
*Backport of Bitcoin GUI PR 319.*
> qt: Rework Open URI dialog

- src/qt/transactionview.cpp
backport from bitcoin #9683
(cherry picked from commit 5424ecff133ea957862d13f3d6c31a5ca27391db)
> cherry-pick: [backport] gui, wallet: random abort (segmentation fault) btc#9683

- src/net_processing.cpp
- src/qt/guiconstants.h
- src/qt/transactiondesc.cpp
- src/qt/transactionrecord.cpp
- src/qt/transactionrecord.h
- src/qt/transactiontablemodel.cpp
- src/validationinterface.cpp
- src/validationinterface.h
- src/wallet/wallet.cpp
- src/wallet/wallet.h
Manual backport of https://github.com/bitcoin/bitcoin/commit/beef7ec4be725beea870a2da510d2817487601ec
CVE-2018-17145
(cherry picked from commit 33fe34ebbba72bc245c901a87f9a3d98912da9a7)
> cherry-pick: backport: Remove useless mapRequest tracking (#19)

- src/support/lockedpool.cpp
Manual backport of bitcoin PR#18443 and bitcoin PR#15633.
Use madvise on Linux and FreeBSD to avoid sensitive data from secure_allocator to be written to swap and core-files.
https://github.com/bitcoin/bitcoin/pull/15600/commits/d831831822885717e9841f1ff67c19add566fa45
https://github.com/bitcoin/bitcoin/pull/18443/commits/f85203097f78d9daa1d35c4097a80beab31da2a4
(cherry picked from commit 7170b3ef04a0fd00f6fcd8212a7a0fc13e289e29)
> cherry-pick: lockedpool: avoid sensitive data in core files (Linux and FreeBSD) (#21)

- src/wallet/wallet.h
Manual backport of bitcoin PR #16572
(cherry picked from commit e8a4f50c1df6f7f6ff852f7f0ae2d7752b03028a)
> cherry-pick: backport: wallet: Fix Char as Bool in Wallet (#23)

- src/net.h
Manual backport of bitcoin PR #17906
Initialize CConnman byte counters during construction, so GetTotalBytesRecv()
and GetTotalBytesSent() methods don't return garbage before Start() is called.
Change shouldn't have any effect outside of the GUI. It just fixes a race
condition during a qt test that was observed on travis:
https://travis-ci.org/bitcoin/bitcoin/jobs/634989685
(cherry picked from commit bb9ee5fae29f582c10895661adf646eaf3eaeb9f)
> cherry-pick: backport: gui: Set CConnman byte counters earlier to avoid uninitialzed reads (#24)

- src/netaddress.cpp
- src/netaddress.h
Manual backport of bitcoin PR 14728
Reachable from either place where SetIP is used when our best-guess
addrLocal for a peer is IPv4, but the peer tells us it's reaching us at
an IPv6 address.
In that case, SetIP turns an IPv4 address into an IPv6 address without
setting the scopeId, which is subsequently read in GetSockAddr during
CNetAddr::ToStringIP and passed to getnameinfo. Fix by ensuring every
constructor initializes the scopeId field with something.
(cherry picked from commit 97eaa1f16f70d16029fa1bbbb115eff644deea55)
> cherry-pick: backport: fix uninitialized read when stringifying an addrLocal (#26)

- src/net.h
- src/net_processing.cpp
Manual backport of bitcoin PR #13907
The largest sensible size for a locator is log in the number of blocks.
But, as noted by Coinr8d on BCT a maximum size message could encode a
hundred thousand locators.  If height were used to limit the messages
that could open new attacks where peers on long low diff forks would
get disconnected and end up stuck.
Ideally, nodes first first learn to limit the size of locators they
send before limiting what would be processed, but common implementations
back off with an exponent of 2 and have an implicit limit of 2^32
blocks, so they already cannot produce locators over some size.
This sets the limit to an absurdly high amount of 101 in order to
maximize compatibility with existing software.
(cherry picked from commit …
> cherry-pick: backport: Introduce a maximum size for locators. (#27)

- depends/packages/libevent.mk
- doc/dependencies.md
Update libevent to 2.1.12-stable.
https://raw.githubusercontent.com/libevent/libevent/release-2.1.12-stable/ChangeLog
(cherry picked from commit 9e43a43c0fcc9678aecbd0b1fff84eb12aee9162)
> depends: libevent update (#32)

- src/qt/walletmodeltransaction.cpp
- src/qt/walletmodeltransaction.h
(cherry picked from commit 917eba9075c403c457d88c8920e8ae4049136208)
> cherry-pick: [qt] Fix potential memory leak in newPossibleKey(ChangeCWallet *wallet) (#45)

- src/qt/reissueassetdialog.cpp
- src/qt/restrictedfreezeaddress.cpp
Backport:
> Disable units spinbox if max units is already set.
> Set minvalue for spinbox after setting value, to allow
> updates when the number of units in the selected asset is
> lower than the number of units in the previous.
> backport: [qt] Reissue asset spinboxes; disable if unit is max.

- src/qt/createassetdialog.cpp
- src/qt/createassetdialog.h
- src/qt/forms/createassetdialog.ui
- src/qt/forms/reissueassetdialog.ui
- src/qt/reissueassetdialog.cpp
- src/qt/reissueassetdialog.h
Backport
> * Add button to open ipfs-hash in the configured ipfs-viewer.
>  This can be handy to verify your ipfs-hash is correct, before creating the asset.
>
> * Remove a check that enabled the Check Availability button once the `Add IPFS/Txid hash` was enabled.
> backport: [qt] Create and reissue asset views add browse IPFS button

- .github/workflows/c-cpp.yml
Use ubuntu-20.04 image to support older versions of GLIBC. (ubuntu 22.04 will still be able to run this build)
> ci: Use ubuntu-20.04 image

- src/assets/assets.cpp
- src/consensus/consensus.h
- src/validation.cpp
- src/validation.h
This is a **consensus critical** change that fixes a **vulnerability** in the asset layer.  
In its current state this vulnerability *does not* affect the Avian main-net but could once assets go live without this fix.
It is **urgent** that this PR is tested and merged before 4.1 is released.
This change will **not** cause a soft fork since assets are not deployed but it may effect local testnet/regtest.
> [URGENT] consensus: Enforce asset coinbase checks and enforced values.

- src/assets/assets.cpp
Backport PR:
> 
Fix bug in memory check
Use .at instead of [] checking as this is the correct way to access memory in a map
rename temp object
> backport: Fix bug with in memory qualifier address checking

- src/consensus/consensus.h
- src/rpc/rawtransaction.cpp
- src/script/sign.cpp
- src/validation.cpp
- src/validation.h
- src/wallet/wallet.cpp
This PR does **2** things:
- [trival: Remove unused IsUAHFForAssetsenabled](https://github.com/AvianNetwork/Avian/commit/984b3a4366639085ca864fb54a64523be2c15d13)
- [trival: Rename ambiguous UAHF to state FORKID](https://github.com/AvianNetwork/Avian/commit/67f8bf66444155fcc3857124914f6eba6ac75b3f)
While these changes are trivial renames, they are **consensus critical** and MUST be tested rigorously.
> trivial: Rename ambiguous UAHFs (FORKID and unused assets)

- src/chainparams.cpp
Use correct BIP44 cointype for mainnet (921).
> chain: Use correct BIP44 cointype for mainnet (921)

- src/validation.cpp
This PR skips check header (PoW), only when downloading headers.
This reduces a bottleneck when downloading block headers during the initial block download.
Tested on mainnet with IBD speed increase of ~22%
Skipped `CheckProofOfWork()` in `pow.cpp` when accepting headers (during IDB).
`CheckProofOfWork()` is already checked in several places. 
`CheckProofOfWork()` is called by `CheckBlock()` which is called multiple times.
In `CheckBlock()`
```cpp
// Check that the header is valid (particularly PoW).  This is mostly
// redundant with the call in AcceptBlockHeader.
if (!CheckBlockHeader(block, state, consensusParams, fCheckPOW))
return false;
```
> validation: Do not check PoW when downloading headers during IBD

- src/qt/forms/overviewpage.ui
- src/qt/guiconstants.h
- src/qt/overviewpage.cpp
- src/qt/platformstyle.cpp
- src/qt/res/css/Dark.css
- src/qt/res/css/Light.css
This PR fixes UI bugs found in 4.1.
Changes include:
- [qt: Fix menubar styling](https://github.com/AvianNetwork/Avian/commit/74ef0893fbebb03bed99c137861a33906f4ce511)
- [qt: Fix assets frame on overview page](https://github.com/AvianNetwork/Avian/commit/69f8276dcb889d16d8d2c6ff602a21ca7152534e)
- [qt: Change light mode shadow color](https://github.com/AvianNetwork/Avian/commit/505cab8845d5ad9aa21429d80c09c0743de5aafa)
- [qt: Fix overview page](https://github.com/AvianNetwork/Avian/commit/1d60768803490aae6d6e6cefea671ae48dd19eb1)
- [qt: Add QScrollBar styling](https://github.com/AvianNetwork/Avian/commit/d0ffce7ebd723a5028176b66e34bd3aca6a30c91)
Tested on Linux x86_64 using regtest with assets.
This PR will stay in draft until it has been fully tested on Windows (mainnet + regtest).
> qt: 4.1 UI fixup

- src/qt/overviewpage.cpp
This PR fixes a potential segfault when attempting to get user info from a nullptr wallet model.
> qt: Check wallet model to prevent segfault

- src/chainparams.cpp
This PR removes the "backup" nodes found in `chainparams.cpp`. This is *not* needed since the DNS seeder is in place to assist new nodes in finding peers.
> trival: Remove "backup" nodes

- src/chainparams.cpp
This PR updates `chainparams.cpp` with updated main-net information.
All values are based on block 1072359 (00000000005ab90c287e481b1f2911228d26723ac07bcadd65031158ad733316).
To check against your node:
```
getblockheader 00000000005ab90c287e481b1f2911228d26723ac07bcadd65031158ad733316
```
To check ChainTxData:
```
getchaintxstats 4096 00000000005ab90c287e481b1f2911228d26723ac07bcadd65031158ad733316
```
Full reindex was successfully completed with these parameters.
> chain: Update assumed chain params

- .github/workflows/c-cpp.yml
- src/Makefile.am
- src/algo/hash_algos.h
- src/flat-database.h
- src/init.cpp
- src/miner.cpp
- src/pow.cpp
- src/pow.h
- src/primitives/block.cpp
- src/primitives/block.h
- src/primitives/powcache.cpp
- src/primitives/powcache.h
- src/serialize.h
- src/span.h
- src/uint256.cpp
- src/uint256.h
- src/unordered_lru_cache.h
- src/util.h
- src/validation.cpp
This the replacement PR for #128.
This PR creates a `powcache.dat` file in the datadir.
> block: Cache PoW hashs

- src/Makefile.am
- src/bench/checkblock.cpp
- src/blockencodings.cpp
- src/chainparams.cpp
- src/consensus/params.h
- src/consensus/tx_verify.cpp
- src/consensus/tx_verify.h
- src/founder_payment.cpp
- src/founder_payment.h
- src/miner.cpp
- src/primitives/block.h
- src/rpc/mining.cpp
- src/test/assets/asset_tx_tests.cpp
- src/test/sighash_tests.cpp
- src/test/transaction_tests.cpp
- src/txmempool.cpp
- src/validation.cpp
- src/validation.h
- src/version.h
- src/wallet/walletdb.cpp
5% block reward code to AVN foundation wallet
> 5% block reward code to AVN foundation wallet

- depends/packages/zlib.mk
zlib 1.2.12 returns 404 not found, causing CI to fail. 
This PR upgrades zlib to 1.2.13 bringing security improvements.
> depends: Update zlib to 1.2.13

- .github/workflows/c-cpp.yml
This PR updates all of the GitHub Actions to version 3.
> ci: Update to GH actions v3

- src/chainparams.cpp
Remove unneeded code that stated: `//TODO: Take these out`
> trivial: Cleanup chainparams.cpp

- src/validation.cpp
This commit can be reverted safely because now mask out dual algo bits and fixed versionbits bug with 4.0.2 *(backported to 4.1)*.
> Revert "qt: Remove 'Unknown block versions being mined' warning"

- src/rpc/assets.cpp
- src/rpc/rawtransaction.cpp
This PR fixes ANS RPC commands:
[rpc: Fix ANS checking in createrawtransaction](https://github.com/AvianNetwork/Avian/commit/e1f85fd0ea7fd8a6e231cf81e73db6c00f41ed23)
[rpc: Add ANS checking to restricted and reissue](https://github.com/AvianNetwork/Avian/commit/4faccc6a305b2b5276fb565df21639a6e0d5be98)
[rpc: Add ANS info to verbose listassets](https://github.com/AvianNetwork/Avian/commit/52159d898d84b54e35022714b8d80030f2dfb95f)
> rpc: Fix ANS for RPC commands "createrawtransaction" and "listassets"

- src/aviand.cpp
- src/chainparams.cpp
- src/chainparams.h
- src/init.cpp
- src/primitives/block.cpp
- src/primitives/block.h
- src/qt/avian.cpp
New version of #90 adapted for v4.2.0
```
This replaces the hard-coded timestamps in block.cpp with the correct Params() timestamp. This commit also changes regtest to use GetX16RHash() since the first block uses X16R and not the dual-algo system.
```
Mainnet, testnet, regtest work as intended.
> consensus: Use chain-specific params when calculating PoW hash

- src/init.cpp
Fixes #188
When the powcache.dat file becomes corrupt due to forced shutdown, loss-of-power, or other conditions the wallet will return an error. This PR makes clear what the end-user should do to fix the problem; therefore, we are more verbose in this error.
> qt+init: Make PoW cache error more verbose
